export default [
  {
    name: 'Анастасия Котович',
    position: 'Team Lead',
    email: 'nastya.kotovich07@gmail.com',
    list: [
      'rhstruetuyfiryfir78ir67ir676e',
      'rhstruetuyfiryfir78ir67ir676e',
      'rhstruetuyfiryfir78ir67ir676e',
      'rhstruetuyfiryfir78ir67ir676e',
      'rhstruetuyfiryfir78ir67ir676e',
      'rhstruetuyfiryfir78ir67ir676e',
    ],
  },
  {
    name: 'Павел Свирид',
    position: 'Front-end developer',
    email: 'psvirid@gmail.com',
    list: [
      'Написал игру Fillword',
      'Помогал по проекту, консультировал',
      'Участвовал в продумывании структуры проекта',
    ],
  },
  {
    name: 'Евгения Габрикова',
    position: 'Front-end developer',
    email: 'gabriellji@yahoo.com',
    list: [
      'Написала игру English Puzzle',
      'Реализовала Promo Page',
      'Помогала по проекту, консультировал',
      'Участвовала в продумывании структуры проекта',
      'Разработала и реализовала Tooltips главной страницы',
    ],
  },
  {
    name: 'Алексей Шевченко',
    position: 'Front-end developer',
    email: 'kamikozz@mail.ru',
    list: [
      'Создал модуль-обёртку обработки ошибок',
      'Написал игру Speakit, согласно технологии SPA',
      'Написал компонент модального окна',
      'Помогал по проекту, консультировал',
      'Помогал с версионным контролем',
      'Разработал дизайн промо-страницы',
      'Участвовал в продумывании структуры проекта',
      'Помогал в с webpack, husky и pre-commit hooks',
      'Написал компонент глобальной статистики',
      'Рассмотрел PR, оставлял замечания, комментарии, неточности и баги',
    ],
  },
  {
    name: 'Антон Мулярчук',
    position: 'Front-end developer',
    email: 'antowa_muliarchyk@mail.ru',
    list: [
      'Написал игру Savannah',
      'Написал игру Audio Call',
      'Помогал по проекту, консультировал',
      'Участвовал в продумывании структуры проекта',
      'Рассмотрел PR, оставлял замечания, комментарии, неточности и баги',
    ],
  },
  {
    name: 'Татьяна Томина',
    position: 'Front-end developer',
    email: 'tominanusha@gmail.com',
    list: [
      'Написала игру Sprint',
      'Реализовала классы Registration и Login для promo страницы',
      'Сделала общий класс Api для взаимодействия с бэкендом',
      'Реализовала классы Words, StartPage, Statistics',
      'Помогала по проекту, консультировал',
      'Участвовала в продумывании структуры проекта',
      'Рассмотрела PR, оставлял замечания, комментарии, неточности и баги',
    ],
  },
];
